// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCecmZf6IHFT72Q1NEio6UQpSF3fE30CUI',
    appId: '1:457644452739:web:f5a6b28a15d29dc57264b6',
    messagingSenderId: '457644452739',
    projectId: 'rafiq-student-app',
    authDomain: 'rafiq-student-app.firebaseapp.com',
    storageBucket: 'rafiq-student-app.firebasestorage.app',
    measurementId: 'G-T2Y3XWJQ74',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCrZxFjV1K3jghhe_i_K3CfN3I5-2YQ48c',
    appId: '1:457644452739:android:cf7095570c733a777264b6',
    messagingSenderId: '457644452739',
    projectId: 'rafiq-student-app',
    storageBucket: 'rafiq-student-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBIruQqUd-H5XlUhdxcFR-PEGSe7wFfuWI',
    appId: '1:457644452739:ios:b700528253da38db7264b6',
    messagingSenderId: '457644452739',
    projectId: 'rafiq-student-app',
    storageBucket: 'rafiq-student-app.firebasestorage.app',
    iosBundleId: 'com.example.student',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBIruQqUd-H5XlUhdxcFR-PEGSe7wFfuWI',
    appId: '1:457644452739:ios:b700528253da38db7264b6',
    messagingSenderId: '457644452739',
    projectId: 'rafiq-student-app',
    storageBucket: 'rafiq-student-app.firebasestorage.app',
    iosBundleId: 'com.example.student',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCecmZf6IHFT72Q1NEio6UQpSF3fE30CUI',
    appId: '1:457644452739:web:ede5ed08b94841a17264b6',
    messagingSenderId: '457644452739',
    projectId: 'rafiq-student-app',
    authDomain: 'rafiq-student-app.firebaseapp.com',
    storageBucket: 'rafiq-student-app.firebasestorage.app',
    measurementId: 'G-Y0GWYH2LE5',
  );
}
